# Generated by Django 3.2.8 on 2021-10-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_product_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sku',
        ),
    ]
